### ISSUE TITLE
Add Flux CLI and Helm

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/not-a-build-harness#37]
We need to do Flux stuff and Helm stuff, so we need those tools installed.

**Comment by zack-is-cool** [comment]
Do we also want to add sops? How about velero,istio and other stuff? I wrote some logic around adding this stuff based on BB version a while ago.

**Comment by RothAndrew** [comment]
Yep, we're adding things as they are identified as needed. Please create an issue with the tools you would like to see added.

**Comment by RothAndrew** [comment]
Yep, we're adding things as they are identified as needed. Please create an issue with the tools you would like to see added.
